<?php echo "<?xml version='1.0' encoding='UTF-8'?>"; ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <url>
    <loc><?php echo Home_Controller_Index::getUrl("index", "index", array(), true); ?></loc>
  </url>
  <url>
    <loc><?php echo Home_About_Controller_Index::getUrl("index", "index", array(), true); ?></loc>
  </url>
  <?php foreach($datas as $url): ?>
  <url>
  	<loc><?php echo $url; ?></loc>
  </url>
  <?php endforeach; ?>
</urlset>