<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<div>
	<div class="group register create">
		<h1>Demande d'ouverture de compte</h1>
		<h3>L'ouverture d'un compte pour vous permettra de consulter les informations masqués.</h3>
		<div>
			<form method="post" action="<?php echo Home_Login_Create_Controller_Index::getUrl("index", "create"); ?>">
    			<fieldset>
    				<Legend>Vos informations</Legend>
    				<div class="group">
    					<div class="col col-2">
    						<label for="firstname">Prénom <em>*</em></label>
    					</div>
    					<div class="col col-10">
    						<input type="text" name="firstname" data-validation="required" value="<?php echo (isset($datas["error"]) ? $datas["content"]["firstname"] : ""); ?>"/>
    					</div>
    				</div>
    				<div class="group">
    					<div class="col col-2">
    						<label for="lastname">Nom <em>*</em></label>
    					</div>
    					<div class="col col-10">
    						<input type="text" name="lastname" data-validation="required" value="<?php echo (isset($datas["error"]) ? $datas["content"]["lastname"] : ""); ?>" />
    					</div>
    				</div>
    				<div class="group">
    					<div class="col col-2">
    						<label for="email">Email <em>*</em></label>
    					</div>
    					<div class="col col-10">
    						<input type="text" name="email" data-validation="required" value="<?php echo (isset($datas["error"]) ? $datas["content"]["email"] : ""); ?>" />
    					</div>
    				</div>
    				<div class="group">
    					<div class="col col-2">
    						<label for="password">Mot de passe <em>*</em></label>
    					</div>
    					<div class="col col-10">
    						<input type="password" name="password" data-validation="required" />
    					</div>
    				</div>
    				<div class="group">
    					<div class="col col-2">
    						<label for="password2">Resaisir le mot de passe <em>*</em></label>
    					</div>
    					<div class="col col-10">
    						<input type="password" name="password2" data-validation="confirmation" data-validation-confirm="password" />
    					</div>
    				</div>
    				<div class="group">
    					<div class="col col-2">
    						<label for="comments">Commentaires <em>*</em></label>
    					</div>
    					<div class="col col-10">
    						<textarea name="comments" rows="8" placeholder="Merci de détailler la raison de votre demande d'ouverture de compte" data-validation="required"><?php echo (isset($datas["error"]) ? $datas["content"]["comments"] : ""); ?></textarea>
    					</div>
    				</div>
    				<?php if(isset($datas["error"])):?>
        			<div class="error">
        				<?php echo $datas["error"]; ?>
        			</div>
        			<?php endif;?>
    			</fieldset>
    			<div class="group button">
    				<div class="col col-12">
    					<div class="g-recaptcha" data-sitekey="<?php echo Core_Config::getConfigValue("captcha/siteKey"); ?>"></div>
    					<br />
    					<input type="submit" class="button red" value="Valider">
    				</div>
    			</div>
    		</form>
		</div>
	</div>
</div>
<script type="text/javascript">
    $.validate({
    	lang: "fr",
    	decimalSeparator: '.',
    	modules : 'security'
    });
</script>
