<div id="wrapper">
	<h1>Demande d'ouverture de compte</h1>
	<h2>L'ouverture d'un compte pour vous permettra de consulter les informations masqués.</h2>
	<div class="group register create">
		<div class="col col-12">
			<fieldset>
				<Legend>Vos informations</Legend>
				<div class="group">
					<div class="col col-2">
						<label for="firstname">Prénom</label>
					</div>
					<div class="col col-10">
						<input type="text" name="firstname" />
					</div>
				</div>
				<div class="group">
					<div class="col col-2">
						<label for="lastname">Nom</label>
					</div>
					<div class="col col-10">
						<input type="text" name="lastname" />
					</div>
				</div>
				<div class="group">
					<div class="col col-2">
						<label for="email">Email</label>
					</div>
					<div class="col col-10">
						<input type="text" name="email" />
					</div>
				</div>
				<div class="group">
					<div class="col col-2">
						<label for="password">Mot de passe</label>
					</div>
					<div class="col col-10">
						<input type="password" name="password" />
					</div>
				</div>
			</fieldset>
			<div class="group button">
				<div class="col col-12">
					<div class="g-recatcha">
					</div>
					<a href="#" type="submit" class="button red">Valider</a>
				</div>
			</div>
		</div>
	</div>
</div>