<div class="paper">
	<?php echo $this->callTemplate("paper/paper", $datas); ?>
	<div class="comments">
		<div class="summary">
			<span class="nb"><?php echo $this->callTemplate("paper/summary/content", $datas); ?></span>
		</div>
		<div class="saisie">
			<?php echo $this->callTemplate("paper/saisie/content", $datas); ?>
		</div>
	</div>
</div>
<?php if(!empty($datas["js"])): ?>
<script>
	<?php echo $datas["js"]; ?>
</script>
<?php endif; ?>
<script>
	$(document).on("keyup", ".paper .saisie .new-comment input[type='text']", function() {
		var text = $(this).val();
		var parent = $(this).parent();
		$(this).data("timeout", setTimeout(function() {
			var a = parent.find("a.save");
			if(text.length == 0) {
				a.fadeOut();
			} else {
				a.fadeIn();
			}
		}, 500));
	});

	$(document).on("click", ".paper .saisie .new-comment a.save", function(e) {
		e.preventDefault();
		var text = $(this).parent().find("input[type='text']");

		$.ajax({
			url: "<?php echo Home_Ajax_Paper_Controller_Index::getUrl("index", "addComment"); ?>",
			type: 'POST',
			data: { idPaper: <?php echo $this->params[0]; ?>, idParent: text.attr("data-idparent"), comment: text.val() },
			dataType: "JSON",
			success: function(data) {
				$(".paper .comments .saisie").html(data["saisie"]);
				$(".paper .comments .summary .nb").html(data["summary"]);
			},
			beforeSend: function() {
				$('#loading').show();
			},
			complete: function() {
				$('#loading').hide();
			}
		});
	});

	$(document).on("click", ".paper .comments .history .comment a.reply", function(e) {
		var li = $(this).closest("li");
		
		$.ajax({
			url: "<?php echo Home_Ajax_Paper_Controller_Index::getUrl("index", "reply"); ?>",
			type: 'POST',
			data: { rang: li.attr("data-rang"), idParent: li.attr("data-id") },
			success: function(data) {
				$(data).insertAfter(li);
				
			},
			beforeSend: function() {
				$('#loading').show();
			},
			complete: function() {
				$('#loading').hide();
			}
		});
	});

	$(".paper .content pre code").each(function(i, block) {
	    hljs.highlightBlock(block);
	});
</script>











