<div class="home">
	<div class="group">
    	<div class="col col-2">
    		<img src="/images/moi.jpg">
    	</div>
    	<div class="col col-10">
    		<div class="presentation">
    			<h1>Chef de projet et lead developpeur en génie logiciel</h1>
    			<div class="content">
        			<p>
        				A 12 ans, avec le premier ordinateur de ma mère, un Amstrad PC 1640, j'ai conçu mon premier jeu vidéo.
        				Ce n'était pas une très grande réussite, mais je venais, sans le savoir, d'attraper le virus !
        			</p>
        			<p>
        				Je n'ai depuis jamais cesser d'écrire des programmes de diverses utilités, à l'aide de différents langages, pour diverses platformes, pour finir par en faire mon métier.
        			</p>
        			<p>
        				Je suis aujourd'hui chef de projet, avec systématiquement plusieurs réalisations à mener à bien en même temps.
        				Mes attributions vont de la relation clientèle à la conception en passant par le développement proprement dit.
        			</p>
        			<p>
        				Et après bientôt 20 ans de métier dans divers secteurs d'activités, j'ai toujours autant de plaisir à transformer une idée humaine en un logiciel fiable et performant.
        			</p>
    			</div>
    		</div>
    	</div>
    </div>
    <div class="papers">
    	<?php foreach($datas as $year => $papers): ?>
    	<h2><?php echo $year; ?></h2>
    	<ul>
    		<?php foreach($papers as $idPaper => $paper): ?>
    			<li>
    				<a href="<?php echo Home_Paper_Controller_Index::getUrl("index", "index", array($idPaper)); ?>">
    					<span class="title"><?php echo $paper["title"]; ?></span>
    					<time class="date"><?php echo $paper["date"]; ?></time>
    				</a>
    			</li>
    		<?php endforeach; ?>
    	</ul>
    	<?php endforeach; ?>
    </div>
</div>

