<!DOCTYPE html>
<html>
	<head>
    	<?php echo $this->callTemplate("page/head", $datas); ?>
    	<script src="https://apis.google.com/js/plusone.js">
			{lang: 'fr'}
		</script>
    </head>
    <body>
    	<?php echo $this->callTemplate("page/header"); ?>
    	<?php echo $this->callTemplate("page/navigation"); ?>
    	<div id="wrapper">
    		<?php echo $this->callTemplate("page/breadcrumb"); ?>
    		<?php echo $this->callTemplate("page/body", $datas); ?>
    	</div>
    	<?php echo $this->callTemplate("page/footer"); ?>
    </body>
</html>
