<div id='loading' style='display: none;'></div>
<?php if($this->showSocialNetwork()): ?>
<div id="social-network">
	<a href="http://www.facebook.com/sharer.php?u=<?php echo $this->getCurrentUrl(); ?>" target="_blank">
		<img src="/images/facebook.png" width="30px" > 
  	</a>
  	<a href="http://twitter.com/share?url=<?php echo $this->getCurrentUrl(); ?>" target="_blank">
		<img src="/images/twitter.png" width="30px">
	</a>
	<a href="http://www.linkedin.com/shareArticle?mini=true&url=<?php echo $this->getCurrentUrl(); ?>" target="_blank">
		<img src="/images/linkedin.png" width="30px">
	</a>
	
	<a href="mailto:<?php echo str_rot13("corentin.lebail@gmail.com"); ?>" class="rot13-a" data-mail="<?php echo str_rot13("corentin.lebail@gmail.com"); ?>" target="_blank">
		<img src="/images/icon-30x30-contact-letter.png">
	</a>	
</div>
<?php endif; ?>
<?php if(!Core_Session::getInstance()->hasData(Home_Modele_Index::COOKIE_SESSION_NAME)): ?>
<div id='cookie_info'>
	<span>Ce site utilise des cookies pour collecter des données statistiques sur la navigation des utilisateurs. En poursuivant votre navigation sur ce site, vous en acceptez l'utilisation.</span>
	<a href="#"><button>Ok</button></a> 
</div>
<?php endif; ?>
<?php $this->renderBody($datas); ?>
<script>
$("#social-network .rot13-a").each(function() {
	var str = $(this).attr("data-mail");

	str = str.replace(/[a-zA-Z]/g,function(c){return String.fromCharCode((c<="Z"?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);});

	$(this).attr("href", "mailto:"+str);
	$(this).attr("data-mail", "");
});

$("#cookie_info a").click(function(e) {
	e.preventDefault();
	$("#cookie_info").hide();

	$.ajax({
		url: "<?php echo Home_Ajax_Controller_Index::getUrl("index", "valideCookies"); ?>",
		type: 'POST',
		success: function(data) {
		},
		beforeSend: function() {
		},
		complete: function() {
		}
	});
});
</script>
</body>