<header>
	<a id="logo" href="<?php echo Home_Controller_Index::getUrl(); ?>">Corentin Lebail</a>
	<div class="navigation">
		<?php echo $this->callTemplate("page/header/navigation")?>	
    </div>
    <a href="https://github.com/clebail" class="github" target="blank">
    	<img style="position: absolute; top: 0; left: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_left_gray_6d6d6d.png" alt="Fork me on GitHub">
    </a>
</header>