<?php if($this->asAnalytics()): ?>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-118104152-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-118104152-1');
</script>

<?php endif; ?>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="author" content="Corentin Lebail" />
<meta name="description" content="<?php echo $this->getDescription($datas); ?>" />
<meta name="keywords" content="<?php echo $this->getKeywords($datas); ?>" />
<link rel="icon" type="image/png" href="/images/favicon.png" />
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<title><?php echo $this->getTitle($datas); ?></title>
<?php echo $this->callTemplate("page/head/css"); ?>
<?php echo $this->callTemplate("page/head/js"); ?>
<?php echo $this->getJSONLD($datas); ?>