<ul>
    <li>
		<a href="<?php echo Home_Music_Controller_Index::getUrl(); ?>" title="Musique">
			<i class="material-icons">music_note</i>
		</a>
	</li>
	<li>
		<a href="<?php echo Home_Game_Controller_Index::getUrl(); ?>" title="Jeux">
			<i class="material-icons">videogame_asset</i>
		</a>
	</li>
	<li>
		<a href="<?php echo Home_About_Controller_Index::getUrl(); ?>" title="A propos">
			<i class="material-icons">info</i>
		</a>
	</li>
	<li>
	<?php if(Home_Modele_Index::isLoggedIn()): ?>
		<a href="<?php echo Home_Controller_Index::getUrl("index", "logout"); ?>" class="logout avatar" title="<?php echo Home_Openid_Modele_Abstract::getName(); ?> - Se déconnecter">
			<img src="<?php echo Home_Openid_Modele_Abstract::getAvatar(); ?>" >
		</a>
	<?php else:?>
		<a href="#" class="signin" title="S'identifier" data-dropdown="#dropdown-compte">
    		<i class="material-icons">https</i>
    	</a>
    	<?php echo $this->callTemplate("login/dropdown", array("id" => "dropdown-compte")); ?>
	<?php endif; ?>
	</li>
</ul>
