<ul>
	<li>
		<a href="<?php echo Home_Game_Controller_Index::getUrl(); ?>" class="cache">
			<i class="material-icons">videogame_asset</i>
		</a>
	</li>
	<li>
		<a href="<?php echo Home_About_Controller_Index::getUrl(); ?>" title="A propos">
			<i class="material-icons">info</i>
		</a>
	</li>
	<li>
	<?php if(Home_Modele_Index::isLoggedIn()): ?>
		<a href="<?php echo Home_Controller_Index::getUrl("index", "logout"); ?>" class="logout avatar" title="Se déconnecter">
			<img src="<?php echo Home_Openid_Google_Modele_Index::getImage(); ?>" >
		</a>
	<?php else:?>
		<a href="<?php echo Home_Openid_Google_Controller_Index::getUrl(); ?>" class="signin" title="S'identifier avec Google">
    		<i class="material-icons">https</i>
    	</a>
	<?php endif; ?>
	</li>
</ul>