<!DOCTYPE html>
<html>
	<head>
    	<?php echo $this->callTemplate("page/head/css"); ?>	
    	<?php echo $this->callTemplate("page/head/js"); ?>	
    </head>
    <body>
    	
    </body>
</html>
<header>
	<div class="navigation">
		<ul>
        	<li>
        		<a href="" class="signin" title="Test" data-dropdown="#dropdown-compte">
            		<i class="material-icons">https</i>
            	</a>
            	<?php echo $this->callTemplate("login/dropdown", array("id" => "dropdown-compte")); ?>
        	</li>
        </ul>
    </div>
</header>
<div id="wrapper">
    <div class="paper">
        <div class="content">
        	<div class="comments">
        		<div class="saisie">
                    <dl class="login">
                    	<dt>
                    		<a href="#" title="Vous devez vous identifier pour laisser un commentaire" title="Test" data-dropdown="#dropdown-comment">
                    			<i class="material-icons">https</i>
                    		</a>
                    		<?php echo $this->callTemplate("login/dropdown", array("id" => "dropdown-comment")); ?>
                    	</dt>
                    </dl>
    			</div>
            </div>
        </div>
     </div>
</div>
