<?php if(Home_Modele_Index::isLoggedIn()): ?>
<div class="new-comment">
	<input type="text" placeholder="participer à la discution ..." />
	<a href="" title="valider" style="display:none" class="save">
		<i class="material-icons">done</i>
	</a>
</div>
<?php else: ?>
<dl class="login">
	<dt>
		<a href="#" title="Vous devez vous identifier pour laisser un commentaire" title="Test" data-dropdown="#dropdown-comment">
			<i class="material-icons">https</i>
		</a>
		<?php echo $this->callTemplate("login/dropdown", array("id" => "dropdown-comment")); ?>
	</dt>
</dl>
<?php endif; ?>
<ul class="history">
	<?php foreach($datas["comments"] as $idComment => $comment): ?>
	<li style="padding-left: <?php echo $comment["rang"]*50; ?>px" data-rang="<?php echo $comment["rang"]; ?>" data-id="<?php echo $comment["id"]; ?>">
		<img class="avatar" src="<?php echo $comment["avatar"]; ?>">
		<span class="comment">
			<span class="name"><?php echo $comment["name"]; ?></span>
			<span class="date"><?php echo $comment["date"]; ?></span>
			<span class="content"><?php echo $comment["content"]; ?></span>
			<?php if(Home_Modele_Index::isLoggedIn()): ?>
				<a href="#" class="reply" title="Répondre">
					<i class="material-icons">reply</i>
				</a>
			<?php endif; ?>
		</span>
	</li>
	<?php endforeach; ?>
</ul>